language: objective-c
osx_image: xcode9.2
script:
- xcodebuild build test -workspace MessageKit.xcworkspace -scheme MessageKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
